/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class interpreter_language_VisualBasic */

#ifndef _Included_interpreter_language_VisualBasic
#define _Included_interpreter_language_VisualBasic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     interpreter_language_VisualBasic
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_interpreter_language_VisualBasic_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
